# Custom Exception handlers
class RetryError(Exception):
    pass
    